# Generated by Django 4.2.1 on 2023-05-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
