# Generated by Django 4.2.1 on 2023-05-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
