# Generated by Django 4.2.1 on 2023-05-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='person',
            field=models.IntegerField(null=True),
        ),
    ]
