# Generated by Django 4.2.1 on 2023-06-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_age_post_gender_post_major_post_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='realname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
