# Generated by Django 4.2.1 on 2023-06-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_reciveuser_post_roomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='match',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
