# Generated by Django 4.2.1 on 2023-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='match',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
