# Generated by Django 4.2.1 on 2023-06-07 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_alter_post_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reciveuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
