# Generated by Django 4.2.1 on 2023-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_reciveuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='roomid',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
