# Generated by Django 4.2.1 on 2023-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='roomid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
