# Generated by Django 4.2.1 on 2023-06-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_post_roomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recivename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
